### PR TITLE
Remove debug printlns

### PR DESCRIPTION
**Pull request by stephenjudkins**
I greatly appreciate your earlier fix!

If possible, could you bump another release after this is merged?

### CODE REVIEW

**Review by s3bk — APPROVED** [review]
Oops

**Comment by s3bk** [comment]
published 0.2.2

**Comment by stephenjudkins** [comment]
You rock, anonymous OSS maintainer!

**Comment by s3bk** [comment]
I am glad you are getting this integrated into the image create.

**Pull request merged**
